---
title: Minimal Text
baseurl: "/Minimal-Text"
desc: Un blog pequeño para entradas grandiosas"
about: Soy Ingeniero en Sistemas Computacionales egresado del [Tecnológico de Estudios Superiores de Ecatepec](http://tese.edu.mx/tese2010/). Actualmente imparto clases en el [Instituto Tecnológico de Iztapalapa III](http://itiztapalapa3.edu.mx) y en el [CETiS32](http://cetis32.edu.mx)
image: https://pinto-light.glitch.me/?width=500&height=500&url=https://i.imgur.com/mxUVc2x.jpg&extension=jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 10
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
