---
title: Minimal Text
baseurl: "/Minimal-Text"
desc: Un blog pequeño para entradas grandiosas!
about: Soy Ingeniero en Sistemas Computacionales. Actualmente imparto clases en el Instituto Tecnológico de Iztapalapa III y en el CETiS32
image: https://pinto-light.glitch.me/?width=500&height=500&url=https://cdn5.vectorstock.com/i/1000x1000/72/79/mustaches-for-barbershop-or-mustache-carnival-vector-22267279.jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 10
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
